version: '3.7'
services:

  # PostgreSQL Database
  postgres:
    image: debezium/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: Raymond
      POSTGRES_PASSWORD: Pl@4m@05032004987
      POSTGRES_DB: bitcoin_data
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - postgres_data:/var/lib/postgresql/data

  # Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  # Kafka Connect with Debezium
  kafka-connect:
    image: debezium/connect:2.1
    container_name: kafka-connect
    depends_on:
      - kafka
      - postgres
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
    volumes:
      - kafka_data:/kafka

volumes:
  postgres_data:
  kafka_data:
